const Product=[    
    {
    id: 1,
    title: "Leather Wallet",
    image: ["/product1.png","/product1.png"],
    slug: "leather-wallet",
    price: 1200,
    category: "Clothing",
    description: "A high-quality cotton t-shirt with a stylish design.",
    size: ["S", "M", "L", "XL"],
    color: ["red", "blue", "black"],
    qty: 1,
    discount: 50,
  },
  {
    id: 2,
    title: "Check Shirt",
    image: ["/product3.png","/product3.png"],
    slug: "check-shirt",
    price: 1500, 
    category: "Accessories",
    description: "A premium leather wallet with multiple compartments.",
    size: ["S", "M", "L", "XL"],
    color: ["red", "blue", "black"],
    qty: 1,
    discount: 100,
  },
  {
    id: 3,
    title: "Jeans",
    image: ["/product4.png","/product4.png"],
    slug: "jeans",
    price: 3000,
    category: "Footwear",
    description: "Comfortable and durable running shoes for daily wear.",
    size: ["S", "M", "L", "XL"],
    color: ["red", "blue", "black"],
    qty: 1,
    discount: 150,
  },
  {
    id: 4,
    title: "Plan-T-Shirt",
    image: ["/sell3.png","/sell3.png"],
    slug: "plan-t-shirt",
    price: 5000,
    category: "Electronics",
    description: "A sleek smart watch with fitness tracking features.",
    size: ["S", "M", "L", "XL"],
    color: ["red", "blue", "black"],
    qty: 1,
    discount: 100,
  },
]
export default Product;